---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: true
    toc_float: true
    number_sections: true
editor_options:
  chunk_output_type: console
---

Welcome to my research website. This project is about the prediction of Alzheimer's Disease using the data from UK Biobank.

The initial set was filtered by Xinqi and large datasets can be found on Google Drive [(click here)](https://drive.google.com/drive/folders/1PzFhnpN-lGwz_RTdPB_tuM99JuwOCNfp?usp=sharing). From my end I will apply statistical techniques to analyze the set while Xinqi would try some ML approaches. The comparison will be made on each step.

Outline of each section:

- Section 1. Preprocess data
- Section 2. Generation of phenotypes without matching using different inputs and methods
- Section 3. Introducing sample matching to generate phenotypes
- Section 4. Evaluation of methods (4.1. prediction; 4.2. association results)
- Section 5. Others

We sometimes run the same method/input more than once based on different settings of parameters, and the most reasonable version is annotated in bold.

# Preprocess data

## Family history data

We pre-process the family history data of UK Biobank in the following two ways. The clean data is uploaded to Google Drive named as `20210512_data.csv` [(download)](https://drive.google.com/file/d/1dvUJ01Ld6Hws6XiBK6kxQaa54yu8qQJn/view?usp=sharing).

- [20210130: data import and basic statistics](20210130-data_import.html): uses `for` loop in R thus it is a very low-efficient way. But it is more direct and easier to understand.
  - [20210131: define AD label](20210131-split_diagnosis.html)
  - [20210131: family history info](20210131-split_illnesses_of_relative.html).

- [20210322: Chapter: input variables](20210322-MICE.html#Input_variables): Tuses `dplyr` package to extract variables and clean up the data. Please check Chapters "Package and data import" and "Input variables" in this analysis [20210322: MICE](20210322-MICE.html) for more details.

## Cognitive data

For cognitive features, we include five aspects and transform them into normal [(download)](https://drive.google.com/file/d/1aFbqprgjSEfZ7BamrMZ0GcLhfG6xr28a/view?usp=sharing).

- [20210526: cleaning cognitive features and transformation](20210526_cognitive_features.html): Output data of cognitive features is stored on Google Drive:
  - 20210615: untransformed [(download)](https://drive.google.com/file/d/1tin6ur-FEcF7dxSfp2fRYZo7zwc-SJyy/view?usp=sharing)
  - 20210703: transformed to normal [(download)](https://drive.google.com/file/d/1aFbqprgjSEfZ7BamrMZ0GcLhfG6xr28a/view?usp=sharing)

## Additional 171 features

Those 171 features are selected by Xinqi and we calculate their Pearson correlations with AD label in the following analysis. The data is already included in `20210512_data.csv` [(download)](https://drive.google.com/file/d/1dvUJ01Ld6Hws6XiBK6kxQaa54yu8qQJn/view?usp=sharing).

- [20210422: Pearson correlation of 171 features](20210422-AdditionalVariablesAmong170.html)

## Other phenotypes

We also study other phenotypes in this project, when we develop the sample matching strategy. The problem with AD is that the patients are usually too old to be included in UK Biobank, leading to the fact that we only have ~1220 AD cases among 501,492 individulas. Thus we select other diseases and perform the same method.

### Age-related hearing impairment

Here we select AGHI because Suzanne and Diana have done a lot about the hearing impairment and we can start from their pipeline.

- [20220601: hearing impairment data](20220601_hearing_impairment_data.html)

# Generation of phenotypes (no matching at all)

We apply two methods (`MICE` and `PU learning`) to generate the phenotypes based on different inputs (`FH`, `FH+COG`, and `COG`). To compare with the published results LT-FH, we also run `LT-FH` on our own.

## Input: only family history

Family history includes three variables: `AD_father`, `AD_mother`, and `AD_siblings`.

- [**20220408: LT-FH on UK Biobank**](20220408_LT-FH_and_matching_kNN.html#Whole_set): apply `LT-FH` on the UK Biobank dataset without defining any controls (prevalence = 5% for both parents and children).
  - [20210518: LT-FH on UK Biobank](20210518_Liability_UKBiobankData_train_test.html): the prevalence is set as 0.22% for children, 5.18% for parents according to Zihan's code.
  - [20210413: LT-FH on a test set](20210413_Liability_Testing1.html)
  - [20210414: LT-FH on a toy set](20210414_Liability_Toy_Data.html)
  - [20210416: LT-FH on UK Biobank with 81200 controls](20210416_Liability_UKBiobankData.html)
- [20210521: Logistic regression on UK Biobank](20210521_Logistic_regression_train_test.html): run `logistic regression` on the UK Biobank dataset (with train and test).
  - [20210321: initial try on logistic regression](20210321-logistic_regression_ADlabel.html)
  - [20210326: logistic regression](20210326-Data_Import_and_Logistic_Regression_All_Individuals.html) (without train and test)
  - [20210402: logistic regression with 81200 controls](20210402-Data_Import_Logistic_Regression_Case_Control.html)
- [**20210521: MICE on UK Biobank**](20210521_MICE_train_test.html): apply MICE on the UK Biobank dataset (with train and test).
  - [20210201: initial try on MICE](20210201-mice_input.html)
  - [20210322: MICE on Uk without train and test](20210322-MICE.html)
- PU approaches on UK Biobank dataset
  - [20210522: PU (from Xinqi)](./ipynb/notebook/052221-HeuristicMethodTry_InductivePUlearning_XGBoost.html)
  - [20210524: PU + logistic results (from Xinqi)](./ipynb/notebook/052421-HeuristicMethodTry_InductivePUlearning_LogisticRegression.html)
  - [20211007: PU + logistic results (prevalence = 50%)](20211007_PU_logistic_FH.html)
  - [20210524: PU inductive + XGBoost + LT-FH + FH (from Xinqi)](./ipynb/notebook/052421-HeuristicMethodTry_InductivePUlearning_XGBoost_LiabilityScore.html)
  - [20211001: PU out-of-bag + XGBoost](20211001_PUoob_FH_only.html)
  - [20210930: PU out-of-bag + XGBoost with train and test (prevalence = 50%)](20210930_PU_only_FH.html)
  - [**20220118: PU out-of-bag + XGBoost without train and test (prevalence = 5%)**](20220118_PUoob_FH_without_matching_prevalence_5_percent.html)
- [20210525: A comparison of methods (precision curves)](20210525_Comparison_of_six_approaches_based_on_family_history_information.html): evaluate different methods by true positive versus positive curves on a test set of 100 AD cases + 2000 noncases.

## Input: family history + cognitive features

### First try: FH + untransformed cognitive features

At first we didn't realize the necessity of transformation of cognitive data, thus we directly applied `logistic regression`, `MICE` and `PU` on the family history and untransformed cognitive data in the following analysis. The results are also compared in precision curves.

- [20210614: logistic regression](20210614_logistic_regression_familyhistory_cognitivefeatures.html)
- [20210615: MICE](20210615_MICE_family_history_and_cognitive_features.html)
- [20210618: PU (from Xinqi)](./ipynb/notebook/061821-PUlearning_XGBoost-CognitiveFeatures_1.html)
- [20210624: A comparison of methods (precision curves) of methods using FH and untransformed cognitive features](20210624_comparison_of_approaches_based_on_family_history_and_cognitive_features.html)

### Revised: FH + transformed cognitive features

After we transformed the data to normal, we reapplied the methods on FH and cognitive features followed by a comparison in precision curves. We also added another comparison to the simplest model too (no fancy models, just impute all missing entries using mean value).

- [20210702: logistic regression](20210702_logistic_regression_family_history_cognitive_features_transformed.html)
- [**20210702: MICE**](20210702_MICE_family_history_and_cognitive_features_transformed.html)
  - [20210717: different age distributions for MICE-FH+COG levels](20210717_distribution_of_age_MICE_score.html)
- [20210801: PU inductive (from Xinqi)](./ipynb/notebook/080121-PUlearning_XGBoost-TransformedCognitiveFeatures_2_inductive.html) 
- [20210801: PU oob (from Xinqi)](./ipynb/notebook/20210801_PUlearning_XGBoost-TransformedCognitiveFeatures_2_oob.html): results stored as `20210722_ADpredict_score_4s.csv` [(download)](https://drive.google.com/file/d/1eUYaDm9pPzpqCNxtcnJgkFDI-FTEq7rY/view?usp=sharing).
- [20211025: PU oob (prevalence = 50%)](20211025_PU_oob_FH_COG.html)
- [**20220118: PU oob (prevalence = 5%)**](20220118_PUoob_FH_COG_without_matching_prevalence_5_percent.html)
- [20210721: A comparison of methods (precision curves)](20210721_comparison_of_approaches_family_history_cognitive_features_transformed.html)
- [20210722: Another comparison with the mean imputation (precision curves)](20210722_model0_mean_imputation_logistic_regression.html) YES!

## Input: family history + cognitive features + 171 features

We apply PU on the all variables (FH + COG + 171 features) to see if the additional features help. We cannot run MICE here because it would take too long.

- [20210728: PU](./ipynb/notebook/072821-PULearning_XGBoost-CognitiveFeatures+171Xinqi.html)
- [20210805: A comparison of methods (precision curves)](20210805_PUXGBoost_171_features.html)

## Input: only cognitive features

During our analysis, we gradually doubt if cognitive features really help improve the results. Thus we also applied methods based on input of only cognitive features.

- [**20211001: MICE on only COG**](20211001_MICE_COG_only.html)
- [**20220118: PU on only COG (prevalence = 5%)**](20220118_PUoob_COG_without_matching_prevalence_5_percent.html)
  - [20211001: PU on only COG (prevalence = 50%)](20211001_PUoob_COG_only.html)

# Sample matching

## Strategy A: A matched set and its generalization

To eliminate the effect of age and sex on the phenotype, we design as follows:

1. Select a subset from all 501492 individuals. The subset includes all the AD cases, and for each case, we matched a fixed number (e.g., 100 or 75) of noncases with exactly same age and sex simultaneously to the case. 
  - [20210727: exact match on age and sex](20210727_match_on_age_and_sex.html) 
  
2. Apply MICE/PU/LTFH methods on this subset with different inputs, thus this score will be free from the effect of age and sex because the input dataset is balanced.

- Input: only FH
  - [**20211111: MICE on only FH (second section)**](20211111_kNN_on_MICE_FH_scores.html#MICE_scores_for_matched_individuals)
  - [**20220118: PU on only FH (prevalence = 5%)**](20220118_PUoob_FH_on_matched_individuals_prevalence_5_percent.html)
    - [20211108: PU on only FH (prevalence = 50%)](20211108_PUoob_FH_matched_only.html)
  - [20220408: LT-FH](20220408_LT-FH_and_matching_kNN.html#Run_LT-FH_on_different_input)
- Input: FH+COG
  - [**20210801: MICE on FH + COG**](20210801_MICE_matched_set_2_FH_cog_transformed.html)
  - [**20220118: PU on FH + COG**](20220118_PUoob_FH_COG_on_matched_individuals_prevalence_5_percent.html)
- Input: COG
  - [**20220118: PU on only COG**](20220118_PUoob_FH_on_matched_individuals_prevalence_5_percent.html)


3. For each individual not in the subset (noncases), we find his/her closest neighbors in the subset based on different assignments (`1.FH`/`2.FH+COG`/`3.FH+AD_self`/`4.FH+COG+AD_self`), and assign the average value of the neighbors' scores to him. Thus everyone has a phenotype score.
- Input: only FH
  - [**20211111: generalization after MICE (FH) (last section)**](20211111_kNN_on_MICE_FH_scores.html) (assignment 1 and 2)
  - [**20211110: generalization after PU (FH) (prevalence = 5%)**](20211110_kNN_on_PU_oob_FH_scores.html) (assignment 1 and 2)
  - [**20220408: LT-FH**](20220408_LT-FH_and_matching_kNN.html#k-NN_to_unmatched_individuals)  (assignment 1,2,3,4)

- Input: FH+COG
  - [20211002: generalization after MICE (FH+COG)](20211002-exact_match_and_kNN_regression.html) (assignment 1 and 2)

## Matching on ADlabels

To analyze if sample matching improves the association results, instead of using the phenotypes generated by MICE/PU/LTFH, we first apply sample matching on the simplest phenotypes, i.e., ADlabel, to see if there is any improvement.

- [20220429: sample matching on ADlabels](20220429_sample_matching_on_ADlabel.html): generate the phenotypes (ADlabels) with the following matching
  - phenotype 0 (full): no sample matching, all individuals (sample size: 501492)
  - phenotype 0: no sample matching, all individuals aged between 50-70 (sample size: 383859)
  - phenotype 1: random sample matching, 1207 ADcases + 1207*75 randomly selected noncases (sample size: 91732)
  - phenotype 2: exact match on age and sex, 1207 ADcases + 1207*75 matched noncases (sample size: 91732)
  - phenotype 3: exact match on age and sex with no family history controls, 1207 ADcases + 1207*36 matched noncases (sample size: 44659)

- [20220520: sample matching on LTFH](20220520_LT-FH_simple_matching.html): generate the phenotypes (LTFH) with the same matching above.

### More cases

Because we only get ~1200 AD cases from UK Biobank, Gao proposes the strategy to treat some noncases as cases, thus we can get more cases. However, even in this way we still get very limited new cases.

- [20220516: matching for more cases](20220516_matching_for_more_cases.html)

### Conditional logistic regression
We found two packages `CGEN` and `survival` can perform conditional logistic regression for our matched dataset.

- [20220530: first try on CGEN package](20220530_CGEN_package.html): run `snp.matched` and `clogit` and compare results (same) on a simulated ovarian cancer set according to the manual book of package `CGEN`.


# Evaluation

The methods are evaluated in two ways, one is prediction and the other is association study. 

## Precision curve comparison

The prediction is performed on a test set of 100 AD cases + 2000 noncases [(download)](https://drive.google.com/drive/u/0/folders/1krX9Yzqf11fpQYVpWQJhx2MLvDsse_Ke), based on different models that we train with different input.

- `P`: A positive (P) sample refers to an individual (from test set) with a predicted score higher than (or equal to) the threshold.
- threshold: we select different quantiles (0.25,, 0.75, 0.95, ...) as the threshold for prediction.
- `N`: A negative (N) sample refers to an individual (from test set) with a predicted score lower than the threshold.
- `TP`: A true positive (TP) sample refers to a case (from test set) with a predicted score higher than (or equal to) the threshold.
- `TN`: A true negative (TN) sample refers to a noncase (from test set) with a predicted score lower than the threshold.
- `FP`: A false positive (FP) sample refers to a noncase (from test set) with a predicted score higher than (or equal to) the threshold.
- `FN`: A false negative (FN) sample refers to a case (from test set) with a predicted score lower than the threshold.


Each evaluation is done for the same input of data/method, and already mentioned in the sections above. We list them here again to make it easier to find.

- [20210525: A comparison of methods (precision curves)](20210525_Comparison_of_six_approaches_based_on_family_history_information.html): input as FH, and compare the following methods
  - logistic regression on FH
  - LT-FH (original)
  - MICE on FH
  - PU + logistic regression on FH
  - PU + XGBoost on FH
  - PU + XGBoost + logistic regression on FH
  - random imputation
- [20210721: A comparison of methods (precision curves)](20210721_comparison_of_approaches_family_history_cognitive_features_transformed.html): input as FH + COG (transformed/untransformed), and compare the following methods
  - LT-FH (original) on FH + COG
  - MICE on FH + COG
  - PU + XGBoost on FH + COG
  - PU + XGBoost + logistic regression on FH + COG
  - random imputation on FH + COG
- [20210805: A comparison of methods (precision curves)](20210805_PUXGBoost_171_features.html): compare the following methods
  - LT-FH (original) on FH + COG
  - MICE on FH + COG
  - PU on FH + COG
  - PU on FH + COG + 170 features
- [20210818: A comparison of methods (precision curves)](20210818_comparison_methods_FH_with_or_without_cog_and_171_features.html): compare the following methods
  - LT-FH (original)
  - MICE on FH
  - PU on FH
  - MICE on FH + COG
  - PU on FH + COG
  - PU on FH + COG + 170 features

## Genome-wide association study

### Generation of phenotypes

- [20210803: generate the phenotype scores based on FH+COG](20210803_generate_covariate_and_phenotype_file_with_normalization.html): generate the following input for association study. Here "transformation" refers to normalization and winsorization.
  - MICE on FH + COG (with and without transformation)
  - PU inductive on FH + COG (with and without transformation)
  - PU oob on FH + COG (with and without transformation)
- [20211004: generate the phenotype scores based on FH/COG](20211004_generate_covariate_and_phenotype_file_with_normalization_2.html): generate the following input for association study:
  - `20211004_covariate_phenotype_MICE_or_PUoob_FH_or_COG.csv`
    - MICE on FH (with and without transformation)
    - MICE on COG (with and without transformation)
    - PU on FH (with and without transformation)
    - PU on COG (with and without transformation)
  - `20211004_covariate_phenotype_MICE_kNN_FH_COG.csv`
    - MICE on FH COG, assignment 2 (with and without transformation)
- [20220115: generate the phenotype scores with strategy A](20220115_generate_phenotype_3.html): generate the following input for association study, all with transformation:
  - PU on FH, no matching
  - PU on FH, assignment 1
  - PU on FH, assignment 2
  - MICE on FH, assignment 1
  - MICE on FH, assignment 2
  - PU on FH + COG, assignment 2

### Manhattan plots and quality control

These files draw the Manhattan plots of some association results and conduct quality control analysis.

- [20210811: SNPs of LT-FH scores](20210811_SNPs_in_2019_NG_LT_FH.html)
- [20210812: SNPs of PU scores](20210812_SNPs_in_PUXGBoost_oob_normalize_winsorized.html)
- [20210812: SNPs of MICE scores](20210812_SNPs_MICE_normalized_winsorized.html)
- [20210905: magma results](20210905_magma_result.html): compare the output of `magma` with and without normalization and normalization

### Evaluation based on Kunkle SNPs

The gold standard is considered to be the SNPs found in [Kunkle et al. 2019](https://www.nature.com/articles/s41588-019-0358-2). 

#### Extract the SNPs from the association results

- [20211009: extract SNPs using R](20211009_comparison_with_Kunkle.html): not recommended. 
- `extract_Kunkle.sh` [(download)](https://drive.google.com/file/d/1NvvORQRfznZn0AuB3Q2JTuYZh0LiWril/view?usp=sharing): This is a shell program with input as the `.snp_stats` and output as only the SNPs in Kunkle paper. The output file is named with additional suffix as `_Kunkle.csv`.

#### Evaluation results on Kunkle SNPs

##### Strategy A

- [**20220327: MICE, PU on different inputs**](20220327_Kunkle_comparison.html): This analysis compares MICE and PU with the original LT-FH and try to answer the following questions:
  1. **Does the Strategy A work (assignment 1 and 2)?**
  
      *Answer*:   
      
                - When the input for generating score is only FH, matching works better than no-matching.
                - When the input for generating score is FH+COG, matching is the same as no-matching.
  2. **Do cognitive features help in the association study?**
  
      *Answer*: Cognitive features don’t really help no matter we use MICE or PU learning to generate scores.
  3. **Which method is better? MICE, PU or LT-FH?**
  
      *Answer*: Generally, MICE performs better on PU on the known 32 SNPs, no matter we use FH or FH+COG as input. However, the results are still not as good as LT-FH.

- [20220420: association results of applying strategy A on LT-FH scores](20220420_LTFH_matching_GWAS_Kunkle.html): including phenotypes generated by original LTFH and LTFH with four assignments in [20220408: LT-FH](20220408_LT-FH_and_matching_kNN.html).


##### Sample matching on ADlabels

- [20220505: association results of applying sample matching on ADlabels](20220505_sample_matching_on_ADlabel_association_results.html): including phenotypes generated in [20220429: sample matching on ADlabels](20220429_sample_matching_on_ADlabel.html).



# Others

## High baseline in PU XGBoost

In the comparison of mean scores in [20210818: A comparison of methods (precision curves)](20210818_comparison_methods_FH_with_or_without_cog_and_171_features.html), we found that PU+XGBoost gets an abnormal high baseline of around 0.4, when using both family history and cognitive features as input. To understand the reason that causes this, we run PU+XGBoost and PU+logistic on different inputs.

- [20211006: baseline comparison analysis](20211006_baseline_of_score.html)

To figure out if it is the high missing rate in the 10 cognitive features themselves cause the high baseline, we select 10 variables with low missing rate in [20211006: baseline analysis](20211006_baseline_of_score.html).

- Input: FH + 10 variables
  - [20211012: PU + XGboost](20211012_PUXGboost_FH_10vars.html)
  - [20211020: logistic regression](20211020_logistic_regression_FH_10var.html)
  - [20211020: PU + logistic regression](20211020_PU_logistic_FH_10var.html)

- Testing different ratios
  - [20211026: PU-FH+COG ratio=1:1](20211026_PU_XGB_FH_COG_1000+1000.html)
  - [20211026: PU-FH+COG ratio=1:10](20211026_PU_XGB_FH_COG_ratio_1over10.html)
  - [20211026: PU-FH+COG on test set](20211026_PU_XGB_FH_COG.html)

## New features (from Ling)

- [20211105: notes from Ling](20211105_notes_ling.html)
- [20211105: summary from Ling](20211105_summary_ling.html)

## Run PU in Jupyter notebook

- [20210715: begin with PU learning in jupyter](20210715_Rui_PULearning_XGBoost_template.html)


## Extension of LT-FH

We design a method to generate the liability scores for both children and their parents.

- [20211125: LT-FH for parents](20211125_LTFH_for_parents.html)
